// backend/src/controllers/accountController.js
// CRUD management for customer accounts — accessible to TELLER role only.
//
// Endpoints:
//   GET  /api/teller/accounts          — list all accounts (search by name/number)
//   GET  /api/teller/accounts/:id      — single account detail
//   POST /api/teller/accounts          — create new account (account_number auto-generated)
//   PUT  /api/teller/accounts/:id      — update account (name, email, balance)
//
// account_number is AUTO-GENERATED by the backend using account_number_seq table.
// pan_linked / pan_number are set only by the HITL approval flow (tellerController).

import { query } from '../db/index.js';
import { v4 as uuidv4 } from 'uuid';
import { emitAuthEvent } from '../ai/governanceSidecar.js';

// ─── Validation helpers ───────────────────────────────────────────────────────

function isValidEmail(email) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

// ─── Auto-generate next account number ───────────────────────────────────────

/**
 * Atomically increment account_number_seq and return the next 10-digit number.
 * Format: '10' prefix + 8-digit zero-padded suffix → e.g. '1000000007'.
 * Falls back to a timestamp-based number if the seq table doesn't exist yet.
 */
async function nextAccountNumber() {
  try {
    const rows = await query`
      UPDATE account_number_seq
      SET last_seq = last_seq + 1
      WHERE id = 1
      RETURNING last_seq
    `;
    if (rows.length) {
      const seq = Number(rows[0].last_seq);
      return '10' + String(seq).padStart(8, '0');
    }
  } catch (_) {
    // seq table not yet created — fall back to timestamp suffix
  }
  // Fallback: use last 8 digits of unix timestamp ms
  return '10' + String(Date.now()).slice(-8);
}

// ─── GET /api/teller/accounts ─────────────────────────────────────────────────

/**
 * List all accounts. Supports optional `?search=` query param that filters
 * by partial match on account_number or full_name (case-insensitive).
 */
export async function listAccounts(req, res) {
  try {
    const { search } = req.query;

    let rows;
    if (search && search.trim()) {
      const term = `%${search.trim()}%`;
      rows = await query`
        SELECT id, account_number, full_name, email, balance, pan_linked, pan_number, created_at
        FROM accounts
        WHERE LOWER(COALESCE(full_name, '')) LIKE LOWER(${term})
           OR account_number::text LIKE ${term}
        ORDER BY created_at DESC NULLS LAST
        LIMIT 100
      `;
    } else {
      rows = await query`
        SELECT id, account_number, full_name, email, balance, pan_linked, pan_number, created_at
        FROM accounts
        ORDER BY created_at DESC NULLS LAST
        LIMIT 100
      `;
    }

    res.status(200).json({ accounts: rows, total: rows.length });
  } catch (err) {
    console.error('[accountController] listAccounts error:', err.message);
    res.status(500).json({ error: 'ERR_LIST_ACCOUNTS_FAILED', message: err.message });
  }
}

// ─── GET /api/teller/accounts/:id ────────────────────────────────────────────

/** Return a single account by UUID. */
export async function getAccount(req, res) {
  try {
    const { id } = req.params;
    const rows = await query`
      SELECT id, account_number, full_name, email, balance, pan_linked, pan_number, created_at
      FROM accounts
      WHERE id = ${id}
      LIMIT 1
    `;
    if (!rows.length) {
      return res.status(404).json({ error: 'ERR_ACCOUNT_NOT_FOUND' });
    }
    res.status(200).json(rows[0]);
  } catch (err) {
    console.error('[accountController] getAccount error:', err.message);
    res.status(500).json({ error: 'ERR_GET_ACCOUNT_FAILED' });
  }
}

// ─── POST /api/teller/accounts ───────────────────────────────────────────────

/**
 * Create a new customer account.
 * Body: { full_name, email, balance? }
 * account_number is AUTO-GENERATED — do not pass it in the request body.
 */
export async function createAccount(req, res) {
  const { full_name, email, balance = 0 } = req.body;

  if (!full_name || !full_name.trim()) {
    return res.status(400).json({ error: 'ERR_MISSING_FULL_NAME', message: 'Full name is required.' });
  }
  if (!email || !isValidEmail(email)) {
    return res.status(400).json({ error: 'ERR_INVALID_EMAIL', message: 'Please provide a valid email address.' });
  }
  if (isNaN(Number(balance)) || Number(balance) < 0) {
    return res.status(400).json({ error: 'ERR_INVALID_BALANCE', message: 'Balance must be zero or a positive number.' });
  }

  const newId       = uuidv4();
  const userId      = uuidv4();
  const accountNum  = await nextAccountNumber();

  try {
    const rows = await query`
      INSERT INTO accounts (id, user_id, account_number, full_name, email, balance, pan_linked)
      VALUES (
        ${newId},
        ${userId},
        ${accountNum},
        ${full_name.trim().toUpperCase()},
        ${email.trim().toLowerCase()},
        ${Number(balance)},
        false
      )
      RETURNING id, account_number, full_name, email, balance, pan_linked, created_at
    `;

    const created = rows[0];
    emitAuthEvent('ACCOUNT_CREATED', { account_number: accountNum, full_name: full_name.trim() }, created.id);
    res.status(201).json(created);
  } catch (err) {
    if (err.message?.includes('unique') || err.message?.includes('duplicate') || err.code === '23505') {
      return res.status(409).json({ error: 'ERR_DUPLICATE_ACCOUNT', message: 'Email address already exists.' });
    }
    console.error('[accountController] createAccount error:', err.message);
    res.status(500).json({ error: 'ERR_CREATE_ACCOUNT_FAILED', message: err.message });
  }
}

// ─── PUT /api/teller/accounts/:id ────────────────────────────────────────────

/**
 * Update an existing account's mutable fields.
 * Body: { full_name?, email?, balance? }
 * account_number and pan_linked are NOT editable here.
 */
export async function updateAccount(req, res) {
  const { id } = req.params;
  const { full_name, email, balance } = req.body;

  if (email !== undefined && !isValidEmail(email)) {
    return res.status(400).json({ error: 'ERR_INVALID_EMAIL', message: 'Please provide a valid email address.' });
  }
  if (balance !== undefined && (isNaN(Number(balance)) || Number(balance) < 0)) {
    return res.status(400).json({ error: 'ERR_INVALID_BALANCE' });
  }

  try {
    const rows = await query`
      UPDATE accounts
      SET
        full_name = COALESCE(${full_name ? full_name.trim().toUpperCase() : null}, full_name),
        email     = COALESCE(${email ? email.trim().toLowerCase() : null}, email),
        balance   = COALESCE(${balance !== undefined ? Number(balance) : null}, balance)
      WHERE id = ${id}
      RETURNING id, account_number, full_name, email, balance, pan_linked, pan_number, created_at
    `;

    if (!rows.length) {
      return res.status(404).json({ error: 'ERR_ACCOUNT_NOT_FOUND' });
    }

    emitAuthEvent('ACCOUNT_UPDATED', { id, updated_fields: Object.keys(req.body) }, id);
    res.status(200).json(rows[0]);
  } catch (err) {
    if (err.message?.includes('unique') || err.message?.includes('duplicate') || err.code === '23505') {
      return res.status(409).json({ error: 'ERR_DUPLICATE_EMAIL', message: 'Email address already in use.' });
    }
    console.error('[accountController] updateAccount error:', err.message);
    res.status(500).json({ error: 'ERR_UPDATE_ACCOUNT_FAILED' });
  }
}

export default { listAccounts, getAccount, createAccount, updateAccount };
